"""
Location Resolver
Scores every file in the codebase index against a RequirementIntent and
returns a ranked list of candidate files + exact symbol/line locations.
Scoring is pure arithmetic over deterministic signals (path tokens, symbol
names, module type, literal content match) — same intent + same index
always yields the same ranking.

If even the best candidate is below MIN_CONFIDENT_SCORE, a "new file"
suggestion is generated by sampling the naming convention of existing files
of the requested module type.
"""
import re
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set

from .codebase_indexer import FileIndex, Symbol
from .requirement_parser import RequirementIntent, _DOMAIN_KEYWORDS

MIN_CONFIDENT_SCORE = 6

# Type-specific phrasing for "no exact symbol matched, but the file is
# the right place" when action == "add".
_ADD_HINT = {
    "api_endpoint": "add a new route/endpoint handler",
    "service": "add a new function/method",
    "database": "add a new model field, class, or migration",
    "ui_component": "add a new component/element",
    "config": "add the new configuration entry",
    "test": "add a new test case",
    "library": "add a new function/helper",
    "module": "add the new logic",
}

# Score weights — kept as named constants so the scoring formula is
# auditable and easy to re-tune without hunting through the method body.
_SCORE_PATH_TOKEN_EXACT = 10
_SCORE_PATH_TOKEN_PARTIAL = 5
_SCORE_SYMBOL_EXACT = 15
_SCORE_SYMBOL_PARTIAL = 8
_SCORE_MODULE_TYPE_MATCH = 6
_SCORE_CONTENT_MATCH = 3
_SCORE_CONTENT_MATCH_CAP = 9
_SCORE_DOMAIN_TOKEN_MATCH = 4


@dataclass
class Candidate:
    path: str
    module_type: str
    score: int
    match_reasons: List[str] = field(default_factory=list)
    matched_symbols: List[Dict] = field(default_factory=list)
    suggestion: str = ""


class LocationResolver:
    def __init__(self, repo_path: Path) -> None:
        self.repo_path = repo_path

    def resolve(
        self,
        intent: RequirementIntent,
        file_indexes: List[FileIndex],
        top_n: int = 5,
    ) -> Dict:
        entity_variants = self._all_entity_variants(intent.entities)

        scored: List[Candidate] = []
        for fi in file_indexes:
            score, reasons, matched_symbols = self._score_file(fi, intent, entity_variants)
            if score <= 0:
                continue
            scored.append(Candidate(
                path=fi.path,
                module_type=fi.module_type,
                score=score,
                match_reasons=reasons,
                matched_symbols=matched_symbols,
            ))

        # Deterministic ordering: score desc, then path asc as tie-break.
        scored.sort(key=lambda c: (-c.score, c.path))
        top = scored[:top_n]

        for c in top:
            c.suggestion = self._build_suggestion(c, intent)

        new_file_suggestion: Optional[Dict] = None
        if not top or top[0].score < MIN_CONFIDENT_SCORE:
            new_file_suggestion = self._suggest_new_file(intent, file_indexes)

        return {
            "candidates": [self._candidate_to_dict(c) for c in top],
            "new_file_suggestion": new_file_suggestion,
        }

    # ------------------------------------------------------------------
    # Scoring
    # ------------------------------------------------------------------

    def _score_file(
        self,
        fi: FileIndex,
        intent: RequirementIntent,
        entity_variants: Dict[str, Set[str]],
    ) -> (int, List[str], List[Dict]):
        score = 0
        reasons: List[str] = []
        matched_symbols: List[Dict] = []
        matched_symbol_keys: Set[str] = set()

        for entity, variants in entity_variants.items():
            # Path token match
            if variants & fi.path_tokens:
                score += _SCORE_PATH_TOKEN_EXACT
                reasons.append(f"path matches '{entity}'")
            else:
                for tok in fi.path_tokens:
                    if any(v in tok or tok in v for v in variants if len(v) >= 3):
                        score += _SCORE_PATH_TOKEN_PARTIAL
                        reasons.append(f"path token '{tok}' relates to '{entity}'")
                        break

            # Symbol name match
            for sym in fi.symbols:
                sym_lower = sym.name.lower()
                key = f"{sym.kind}:{sym.name}:{sym.line}"
                if sym_lower in variants:
                    if key not in matched_symbol_keys:
                        score += _SCORE_SYMBOL_EXACT
                        reasons.append(f"symbol '{sym.name}' ({sym.kind}) matches '{entity}'")
                        matched_symbols.append(self._symbol_to_dict(sym))
                        matched_symbol_keys.add(key)
                elif any(v in sym_lower for v in variants if len(v) >= 3):
                    if key not in matched_symbol_keys:
                        score += _SCORE_SYMBOL_PARTIAL
                        reasons.append(f"symbol '{sym.name}' ({sym.kind}) relates to '{entity}'")
                        matched_symbols.append(self._symbol_to_dict(sym))
                        matched_symbol_keys.add(key)

        # Module type match
        if intent.target_types and fi.module_type in intent.target_types:
            score += _SCORE_MODULE_TYPE_MATCH
            reasons.append(f"file type '{fi.module_type}' matches requested type")

        # Domain token match (e.g. requirement mentions "auth" and the
        # file lives under a path containing an auth-related token)
        for tag in intent.domain_tags:
            keywords = _DOMAIN_KEYWORDS.get(tag, [])
            if any(kw.replace(" ", "") in fi.path_tokens for kw in keywords):
                score += _SCORE_DOMAIN_TOKEN_MATCH
                reasons.append(f"path relates to domain '{tag}'")

        # Literal content match (only for files that already scored —
        # avoids reading every file in the repo for every entity)
        if score > 0 and intent.entities:
            content_score = self._content_match_score(fi, entity_variants)
            if content_score:
                score += content_score
                reasons.append(f"content contains {content_score // _SCORE_CONTENT_MATCH} matching term(s)")

        matched_symbols.sort(key=lambda s: s["line"])
        return score, reasons, matched_symbols

    def _content_match_score(self, fi: FileIndex, entity_variants: Dict[str, Set[str]]) -> int:
        full = self.repo_path / fi.path
        try:
            content = full.read_text(encoding="utf-8", errors="ignore").lower()
        except OSError:
            return 0

        hits = 0
        for variants in entity_variants.values():
            if any(v in content for v in variants if len(v) >= 3):
                hits += 1
        return min(hits * _SCORE_CONTENT_MATCH, _SCORE_CONTENT_MATCH_CAP)

    # ------------------------------------------------------------------
    # Suggestions
    # ------------------------------------------------------------------

    def _build_suggestion(self, c: Candidate, intent: RequirementIntent) -> str:
        if c.matched_symbols:
            locs = ", ".join(f"{s['name']} ({s['kind']} @ line {s['line']})" for s in c.matched_symbols[:3])
            if intent.action == "add":
                return f"Add the new logic near existing related symbol(s): {locs}."
            if intent.action in ("modify", "fix"):
                return f"Modify the following symbol(s): {locs}."
            if intent.action == "remove":
                return f"Remove/clean up the following symbol(s): {locs}."
            return f"Review symbol(s): {locs}."

        if intent.action == "add":
            hint = _ADD_HINT.get(c.module_type, "update this file")
            return f"No exact symbol match — {hint} in this file ({c.module_type}), following its existing conventions."
        return f"No exact symbol match — review/update this {c.module_type} file for the referenced behavior."

    def _suggest_new_file(self, intent: RequirementIntent, file_indexes: List[FileIndex]) -> Optional[Dict]:
        if not intent.target_types:
            return None

        target_type = intent.target_types[0]
        same_type = [fi for fi in file_indexes if fi.module_type == target_type]
        if not same_type:
            return None

        # Most common parent directory for this module type
        dir_counter = Counter(str(Path(fi.path).parent).replace("\\", "/") for fi in same_type)
        folder, _ = dir_counter.most_common(1)[0]

        in_folder = [fi for fi in same_type if str(Path(fi.path).parent).replace("\\", "/") == folder]

        # Naming convention: most common suffix pattern (e.g. *_controller.py, *Controller.cs)
        suffix_counter: Counter = Counter()
        ext_counter: Counter = Counter()
        for fi in in_folder:
            stem = Path(fi.path).stem
            ext_counter[Path(fi.path).suffix] += 1
            m = re.search(r'([A-Z][a-z0-9]+|_[a-z0-9]+)$', stem)
            if m:
                suffix_counter[m.group(1)] += 1

        ext = ext_counter.most_common(1)[0][0] if ext_counter else (in_folder[0].language and Path(in_folder[0].path).suffix or "")
        suffix = suffix_counter.most_common(1)[0][0] if suffix_counter else ""

        entity_name = intent.entities[0] if intent.entities else "NewModule"
        base_name = re.sub(r'[^A-Za-z0-9_]', '', entity_name)

        suggested_name = f"{base_name}{suffix}{ext}" if suffix and suffix[0].isupper() else f"{base_name}{suffix}{ext}"
        example_file = in_folder[0].path

        return {
            "folder": folder,
            "suggested_filename": suggested_name,
            "suggested_path": f"{folder}/{suggested_name}" if folder != "." else suggested_name,
            "module_type": target_type,
            "naming_convention_example": example_file,
            "note": (
                f"No existing file scored highly enough for this requirement. "
                f"Based on the '{target_type}' files already in '{folder}', "
                f"create a new file following the naming convention of "
                f"'{example_file}'."
            ),
        }

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _symbol_to_dict(sym: Symbol) -> Dict:
        return {"name": sym.name, "kind": sym.kind, "line": sym.line, "detail": sym.detail}

    @staticmethod
    def _candidate_to_dict(c: Candidate) -> Dict:
        return {
            "path": c.path,
            "module_type": c.module_type,
            "score": c.score,
            "match_reasons": c.match_reasons,
            "matched_symbols": c.matched_symbols,
            "suggestion": c.suggestion,
        }

    @staticmethod
    def _all_entity_variants(entities: List[str]) -> Dict[str, Set[str]]:
        return {entity: _entity_variants(entity) for entity in entities}


def _entity_variants(entity: str) -> Set[str]:
    """Generate snake_case / kebab-case / camelCase / PascalCase / joined
    forms of an entity so 'discount_code', 'discountCode', 'DiscountCode'
    and 'discount-code' all match each other."""
    variants = {entity.lower()}

    words = [w for w in re.split(r'[_\-\s]+|(?=[A-Z])', entity) if w]
    if words:
        lower_words = [w.lower() for w in words]
        variants.add("_".join(lower_words))
        variants.add("-".join(lower_words))
        variants.add("".join(lower_words))
        variants.add(lower_words[0] + "".join(w.capitalize() for w in lower_words[1:]))
        variants.add("".join(w.capitalize() for w in lower_words))

    return {v.lower() for v in variants if v}
